// <auto-generated />
using System;
using MarketingTaskAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MarketingTaskAPI.Migrations
{
    [DbContext(typeof(MarketingTaskDbContext))]
    partial class MarketingTaskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MarketingTaskAPI.Models.Area", b =>
                {
                    b.Property<int>("AreaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AreaId"));

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("AreaId");

                    b.HasIndex("CityId");

                    b.ToTable("Areas", (string)null);
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.HasIndex("StateId");

                    b.ToTable("Cities", (string)null);
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Contact")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Designation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees", (string)null);
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.EmployeeFeedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("ConsultantName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FeedbackText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("MeetingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("FeedbackId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TaskId");

                    b.ToTable("EmployeeFeedback", (string)null);
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("PincodeId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.HasKey("LocationId");

                    b.HasIndex("AreaId");

                    b.HasIndex("CityId");

                    b.HasIndex("PincodeId");

                    b.HasIndex("StateId");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.Pincode", b =>
                {
                    b.Property<int>("PincodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PincodeId"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LocalityName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PincodeValue")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Pincode");

                    b.HasKey("PincodeId");

                    b.HasIndex("AreaId");

                    b.ToTable("Pincodes", (string)null);
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StateCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("StateId");

                    b.ToTable("States", (string)null);
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.TaskLocation", b =>
                {
                    b.Property<int>("TaskLocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskLocationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomLocation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("TaskLocationId");

                    b.HasIndex("LocationId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskLocations", (string)null);
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.TaskReschedule", b =>
                {
                    b.Property<int>("RescheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RescheduleId"));

                    b.Property<DateTime>("NewDeadline")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NewTaskDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OriginalDeadline")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OriginalTaskDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RescheduleReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RescheduledAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RescheduledByUserId")
                        .HasColumnType("int");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.HasKey("RescheduleId");

                    b.HasIndex("RescheduledByUserId");

                    b.HasIndex("TaskId");

                    b.ToTable("TaskReschedules", (string)null);
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.TaskStatusEntity", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId");

                    b.ToTable("TaskStatuses", (string)null);

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            CreatedAt = new DateTime(2025, 10, 6, 11, 30, 24, 856, DateTimeKind.Utc).AddTicks(3466),
                            IsActive = true,
                            StatusCode = "NOT_STARTED",
                            StatusName = "Not Started"
                        },
                        new
                        {
                            StatusId = 2,
                            CreatedAt = new DateTime(2025, 10, 6, 11, 30, 24, 856, DateTimeKind.Utc).AddTicks(3471),
                            IsActive = true,
                            StatusCode = "IN_PROGRESS",
                            StatusName = "In Progress"
                        },
                        new
                        {
                            StatusId = 3,
                            CreatedAt = new DateTime(2025, 10, 6, 11, 30, 24, 856, DateTimeKind.Utc).AddTicks(3473),
                            IsActive = true,
                            StatusCode = "COMPLETED",
                            StatusName = "Completed"
                        },
                        new
                        {
                            StatusId = 4,
                            CreatedAt = new DateTime(2025, 10, 6, 11, 30, 24, 856, DateTimeKind.Utc).AddTicks(3474),
                            IsActive = true,
                            StatusCode = "POSTPONED",
                            StatusName = "Postponed"
                        },
                        new
                        {
                            StatusId = 5,
                            CreatedAt = new DateTime(2025, 10, 6, 11, 30, 24, 856, DateTimeKind.Utc).AddTicks(3476),
                            IsActive = true,
                            StatusCode = "PARTIAL_CLOSE",
                            StatusName = "Partial Close"
                        });
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.TaskStatusHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Remarks")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("HistoryId");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskStatusHistories", (string)null);
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.TaskTaskType", b =>
                {
                    b.Property<int>("TaskTaskTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskTaskTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TaskId")
                        .HasColumnType("int");

                    b.Property<int>("TaskTypeId")
                        .HasColumnType("int");

                    b.HasKey("TaskTaskTypeId");

                    b.HasIndex("TaskId");

                    b.HasIndex("TaskTypeId");

                    b.ToTable("TaskTaskTypes", (string)null);
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.TaskType", b =>
                {
                    b.Property<int>("TaskTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TaskTypeId");

                    b.ToTable("TaskTypes", (string)null);

                    b.HasData(
                        new
                        {
                            TaskTypeId = 1,
                            CreatedAt = new DateTime(2025, 10, 6, 11, 30, 24, 856, DateTimeKind.Utc).AddTicks(3903),
                            Description = "Meeting with consultant",
                            IsActive = true,
                            TypeName = "Meeting Consultant"
                        },
                        new
                        {
                            TaskTypeId = 2,
                            CreatedAt = new DateTime(2025, 10, 6, 11, 30, 24, 856, DateTimeKind.Utc).AddTicks(3911),
                            Description = "Field work activities",
                            IsActive = true,
                            TypeName = "Field Work"
                        },
                        new
                        {
                            TaskTypeId = 3,
                            CreatedAt = new DateTime(2025, 10, 6, 11, 30, 24, 856, DateTimeKind.Utc).AddTicks(3913),
                            Description = "Follow up activities",
                            IsActive = true,
                            TypeName = "Follow Up"
                        },
                        new
                        {
                            TaskTypeId = 4,
                            CreatedAt = new DateTime(2025, 10, 6, 11, 30, 24, 856, DateTimeKind.Utc).AddTicks(3915),
                            Description = "Documentation tasks",
                            IsActive = true,
                            TypeName = "Documentation"
                        });
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.UserTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<decimal?>("ActualHours")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("AdditionalNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<string>("AreaIds")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AreaNames")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("AssignedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CityName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClientName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CustomLocation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Department")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("Marketing");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeIdNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("EstimatedHours")
                        .HasColumnType("decimal(6,2)");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("bit");

                    b.Property<string>("LocalityName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<int?>("PincodeId")
                        .HasColumnType("int");

                    b.Property<string>("PincodeValue")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ProjectCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("StateName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Not Started");

                    b.Property<string>("TaskCategory")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Field Work");

                    b.Property<DateTime>("TaskDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaskType")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("General");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TaskId");

                    b.HasIndex("AreaId");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("CityId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("LocationId");

                    b.HasIndex("StateId");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.Area", b =>
                {
                    b.HasOne("MarketingTaskAPI.Models.City", "City")
                        .WithMany("Areas")
                        .HasForeignKey("CityId")
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.City", b =>
                {
                    b.HasOne("MarketingTaskAPI.Models.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.EmployeeFeedback", b =>
                {
                    b.HasOne("MarketingTaskAPI.Models.Employee", "Employee")
                        .WithMany("EmployeeFeedback")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketingTaskAPI.Models.UserTask", "Task")
                        .WithMany("EmployeeFeedback")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.Location", b =>
                {
                    b.HasOne("MarketingTaskAPI.Models.Area", "AreaNavigation")
                        .WithMany("Locations")
                        .HasForeignKey("AreaId");

                    b.HasOne("MarketingTaskAPI.Models.City", "CityNavigation")
                        .WithMany("Locations")
                        .HasForeignKey("CityId");

                    b.HasOne("MarketingTaskAPI.Models.Pincode", "PincodeNavigation")
                        .WithMany("Locations")
                        .HasForeignKey("PincodeId");

                    b.HasOne("MarketingTaskAPI.Models.State", "StateNavigation")
                        .WithMany("Locations")
                        .HasForeignKey("StateId");

                    b.Navigation("AreaNavigation");

                    b.Navigation("CityNavigation");

                    b.Navigation("PincodeNavigation");

                    b.Navigation("StateNavigation");
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.Pincode", b =>
                {
                    b.HasOne("MarketingTaskAPI.Models.Area", "Area")
                        .WithMany("Pincodes")
                        .HasForeignKey("AreaId")
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.TaskLocation", b =>
                {
                    b.HasOne("MarketingTaskAPI.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketingTaskAPI.Models.UserTask", "Task")
                        .WithMany("TaskLocations")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.TaskReschedule", b =>
                {
                    b.HasOne("MarketingTaskAPI.Models.User", "RescheduledByUser")
                        .WithMany()
                        .HasForeignKey("RescheduledByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketingTaskAPI.Models.UserTask", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RescheduledByUser");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.TaskStatusHistory", b =>
                {
                    b.HasOne("MarketingTaskAPI.Models.User", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketingTaskAPI.Models.UserTask", "Task")
                        .WithMany("StatusHistory")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketingTaskAPI.Models.User", null)
                        .WithMany("StatusChanges")
                        .HasForeignKey("UserId");

                    b.Navigation("ChangedByUser");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.TaskTaskType", b =>
                {
                    b.HasOne("MarketingTaskAPI.Models.UserTask", "Task")
                        .WithMany("TaskTaskTypes")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MarketingTaskAPI.Models.TaskType", "TaskType")
                        .WithMany("TaskTaskTypes")
                        .HasForeignKey("TaskTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("TaskType");
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.User", b =>
                {
                    b.HasOne("MarketingTaskAPI.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.UserTask", b =>
                {
                    b.HasOne("MarketingTaskAPI.Models.Area", "AreaNavigation")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MarketingTaskAPI.Models.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MarketingTaskAPI.Models.City", "CityNavigation")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MarketingTaskAPI.Models.Employee", "Employee")
                        .WithMany("Tasks")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MarketingTaskAPI.Models.Location", "Location")
                        .WithMany("Tasks")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MarketingTaskAPI.Models.State", "StateNavigation")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MarketingTaskAPI.Models.User", null)
                        .WithMany("AssignedTasks")
                        .HasForeignKey("UserId");

                    b.Navigation("AreaNavigation");

                    b.Navigation("AssignedByUser");

                    b.Navigation("CityNavigation");

                    b.Navigation("Employee");

                    b.Navigation("Location");

                    b.Navigation("StateNavigation");
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.Area", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Pincodes");
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.City", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.Employee", b =>
                {
                    b.Navigation("EmployeeFeedback");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.Location", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.Pincode", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.State", b =>
                {
                    b.Navigation("Cities");

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.TaskType", b =>
                {
                    b.Navigation("TaskTaskTypes");
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.User", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("StatusChanges");
                });

            modelBuilder.Entity("MarketingTaskAPI.Models.UserTask", b =>
                {
                    b.Navigation("EmployeeFeedback");

                    b.Navigation("StatusHistory");

                    b.Navigation("TaskLocations");

                    b.Navigation("TaskTaskTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
