import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { catchError, map } from 'rxjs/operators';
import { environment } from '../../environments/environment';

export interface MarketingCampaignData {
  campaignId?: number;
  campaignManager: string;
  employeeCode: string;
  taskDescription: string;
  taskDate: string;
  deadline: string;
  priority: string;
  isUrgent: boolean;
  stateId: number;
  cityId: number;
  locality: string;
  pincode: string;
  localityId?: number;  //  ADD: Optional locality ID
  pincodeId?: number;   //  ADD: Optional pincode ID
  clientName: string;
  projectCode: string;
  consultantName: string;
  campaignCode?: string; // Auto-generated by backend
  estimatedHours?: number;
  expectedReach?: number;
  conversionGoal: string;
  kpis: string;
  marketingMaterials: string;
  approvalRequired: boolean;
  approvalContact: string;
  budgetCode: string;
  additionalNotes: string;
  consultantFeedback: string;
  selectedTaskTypes: number[];
  status: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface ApiResponse<T> {
  success: boolean;
  message: string;
  data?: T;
  count?: number;
  campaignId?: number;
  campaignCode?: string; // Auto-generated campaign code
  error?: string;
}

@Injectable({
  providedIn: 'root'
})
export class MarketingFormService {
  private apiUrl = `${environment.apiUrl}/marketingcampaign`;

  constructor(private http: HttpClient) { }

  private getHeaders(): HttpHeaders {
    const token = localStorage.getItem('token');
    return new HttpHeaders({
      'Content-Type': 'application/json',
      'Authorization': token ? `Bearer ${token}` : ''
    });
  }


  /**
   * Save marketing campaign form data
   * campaignCode is optional - backend will auto-generate if not provided
   */
  saveMarketingCampaign(campaignData: Partial<MarketingCampaignData>): Observable<ApiResponse<MarketingCampaignData>> {
    const headers = this.getHeaders();

    return this.http.post<ApiResponse<MarketingCampaignData>>(`${this.apiUrl}/save`, campaignData, { headers })
      .pipe(
        map(response => {
          console.log('Marketing campaign saved successfully:', response);
          return response;
        }),
        catchError(this.handleError)
      );
  }

  /**
   * Get a new auto-generated campaign code
   */
  getNewCampaignCode(): Observable<ApiResponse<any>> {
    const headers = this.getHeaders();

    return this.http.get<ApiResponse<any>>(`${this.apiUrl}/newcode`, { headers })
      .pipe(
        map(response => {
          console.log('New campaign code generated:', response);
          return response;
        }),
        catchError(this.handleError)
      );
  }

  /**
   * Get all marketing campaigns
   */
  getAllMarketingCampaigns(): Observable<ApiResponse<MarketingCampaignData[]>> {
    const headers = this.getHeaders();

    return this.http.get<ApiResponse<MarketingCampaignData[]>>(`${this.apiUrl}/all`, { headers })
      .pipe(
        map(response => {
          console.log('Marketing campaigns retrieved successfully:', response);
          return response;
        }),
        catchError(this.handleError)
      );
  }

  /**
   * Get a specific marketing campaign by ID
   */
  getMarketingCampaignById(id: number): Observable<ApiResponse<MarketingCampaignData>> {
    const headers = this.getHeaders();

    return this.http.get<ApiResponse<MarketingCampaignData>>(`${this.apiUrl}/${id}`, { headers })
      .pipe(
        map(response => {
          console.log('Marketing campaign retrieved successfully:', response);
          return response;
        }),
        catchError(this.handleError)
      );
  }

  /**
   * Update marketing campaign
   */
  updateMarketingCampaign(id: number, campaignData: MarketingCampaignData): Observable<ApiResponse<MarketingCampaignData>> {
    const headers = this.getHeaders();

    return this.http.put<ApiResponse<MarketingCampaignData>>(`${this.apiUrl}/${id}`, campaignData, { headers })
      .pipe(
        map(response => {
          console.log('Marketing campaign updated successfully:', response);
          return response;
        }),
        catchError(this.handleError)
      );
  }

  /**
   * Delete marketing campaign
   */
  deleteMarketingCampaign(id: number): Observable<ApiResponse<any>> {
    const headers = this.getHeaders();

    return this.http.delete<ApiResponse<any>>(`${this.apiUrl}/${id}`, { headers })
      .pipe(
        map(response => {
          console.log('Marketing campaign deleted successfully:', response);
          return response;
        }),
        catchError(this.handleError)
      );
  }

  /**
   * Test API connection
   */
  testConnection(): Observable<ApiResponse<any>> {
    const headers = this.getHeaders();

    return this.http.get<ApiResponse<any>>(`${this.apiUrl}/test`, { headers })
      .pipe(
        map(response => {
          console.log('API connection test successful:', response);
          return response;
        }),
        catchError(this.handleError)
      );
  }

  /**
   * Handle HTTP errors
   */
  private handleError(error: any): Observable<never> {
    console.error('Marketing Form Service Error:', error);

    let errorMessage = 'An unknown error occurred';

    if (error.error) {
      if (error.error.message) {
        errorMessage = error.error.message;
      } else if (typeof error.error === 'string') {
        errorMessage = error.error;
      }
    } else if (error.message) {
      errorMessage = error.message;
    }

    // Handle specific HTTP status codes
    if (error.status === 0) {
      errorMessage = 'Unable to connect to server. Please check your internet connection.';
    } else if (error.status === 400) {
      errorMessage = 'Invalid request. Please check your form data.';
    } else if (error.status === 401) {
      errorMessage = 'Unauthorized. Please login again.';
    } else if (error.status === 403) {
      errorMessage = 'Access denied. You do not have permission to perform this action.';
    } else if (error.status === 404) {
      errorMessage = 'Resource not found.';
    } else if (error.status === 500) {
      errorMessage = 'Server error. Please try again later.';
    }

    return throwError(() => ({
      message: errorMessage,
      status: error.status,
      error: error.error
    }));
  }
}
